name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: simonjan2/employee_management_flask_test:latest

    outputs:
      image_updated: ${{ steps.docker_build.outcome == 'success' }}

  # trigger_terraform:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Terraform workflow
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #         event-type: docker-update
  #         client-payload: '{"docker_updated": "true"}'